#########################################################
##### Test: centroids as candidates #####

# This code was used as a test to see how 
# using centroids generated by k-means might fare
# being used as candidate points in the location allocation
# models. 

# Last updated around 9/14/26, with edits and annotations
# made on 10/5/26. 

#########################################################

library(dplyr)
library(tidyr)
library(ggplot2)
library(terra)
library(sf)
library(spopt)
library(stringr)
library(gdistance)
library(patchwork)
library(classInt)

setwd("/Volumes/LaCie")
set.seed(123)

#########################################################
##### Loading in data #####

#For this test, I worked on just a small area of Equateur,
#just south of Mbandaka. Defined that study area here: 
ext <- c(800000, 900000, -40000, 0)

#Load in friction surface
friction_r <- rast("Data/Travel Time Catchments/traveltime_v6.tif")
friction_r <- crop(friction_r, ext)

#Make template for all the data that need to be resampled later
temp <- rast(ext(friction_r), res=100, crs="EPSG:3201")

#Resample the friction surface from 30m to 100m, then convert to a raster
friction_r <- resample(friction_r, temp, method = "bilinear")
friction <- raster::raster(friction_r)
rm(friction_r)

#Load in population data
grid3_100m <- rast("Data/Grid3 Population Estimates/COD_Population_v4_4_gridded.tif")
grid3_100m <- project(grid3_100m, temp)

#Make one dataframe where the each row is populated point
allstack100m <- c(grid3_100m)
names(allstack100m) <- c("pop")
allstack100m <- as.data.frame(allstack100m, xy=TRUE, na.rm=TRUE)

#Make population weighted coordinates matrix for use in making centroids later
weighted_rows <- rep(1:nrow(allstack100m), times = round(allstack100m$pop))
coordinates_matrix <- allstack100m[weighted_rows, c("x", "y")]

#Create weights needed for the Location Allocation model
allstack100m <- st_as_sf(allstack100m, coords=c("x","y"), crs="EPSG:3201")
allstack100m$weight_pop <- log(allstack100m$pop + 1)
#Make a separate spatial object for the demand points
demand_sp  <- as(allstack100m, "Spatial")

#Make transition matrix that will be used to make cost matrix:
conductance <- transition(friction, transitionFunction = function(x) 1 / mean(x), directions = 16)
conductance <- geoCorrection(conductance, type = "c")

#########################################################
##### Generate centroids then run location models #####

#Define the number of centroids desired.
#I chose these as X times the number of facilities I wanted to place.
#In this test, I place 20 facilities, so 3x means 60 centroids, 
#5x means 100 centroids, etc.
ncentroids <- c(60, 100, 200, 400, 600, 800, 1000)

for (i in ncentroids) {
  
  print(i)
  #generate kmeans
  kmeans_result <- kmeans(coordinates_matrix, centers = i, iter.max = 50)
  cand_centroid <- as.data.frame(kmeans_result$centers)
  cand_centroid <- st_as_sf(cand_centroid, coords=c("x","y"), crs="EPSG:3201") 
  cand_centroid <- cand_centroid %>% mutate(centroids=i)
  
  #convert to spatial points
  cand_sp <- as(cand_centroid, "Spatial")
  
  #calculate cost matrix
  print("Making cost matrix")
  cost_matrix <- costDistance(conductance, fromCoords = demand_sp, toCoords = cand_sp)
  time_matrix <- as.matrix(cost_matrix)
  
  #get everything prepped for mclp
  dem <- allstack100m %>% mutate(traveltime = Inf)
  hf_points <- data.frame(geometry=I(list()), id=numeric())
  current_tt <- dem$traveltime
  
  for (j in 1:5) {
    
    print(j)
    
    ###Step 1: Place 1 facility. This MCLP is meant to mimic the 
    #system realignment scenario, so it is blind to existing facilities. 
    mclp_results <- mclp(demand = dem, facilities = cand_centroid, 
                         n_facilities = 1, service_radius = 120,
                         weight_col = "weight_pop", cost_matrix=time_matrix)
    print("Facility placed.")
    
    #Identify which facility was chosen
    index <- which(mclp_results$facilities$.selected)
    #Isolate chosen facility from list of candidates, save to running list of HF
    newfac <- cand_centroid[index,]
    newfac <- newfac %>% dplyr::select(geometry) %>% mutate(id = j)
    hf_points <- rbind(hf_points, newfac)
    
    #Extract travel times to new facility
    newtime <- time_matrix[,index]
    current_tt <- pmin(current_tt, newtime, na.rm=TRUE)
    dem$traveltime <- current_tt
    
    #Update weights - if travel time <120, change to 0
    dem$weight_pop[dem$traveltime <= 120] <- 0
    
    #Status update and add to counter
    print(paste("Max: ", round(max(dem$traveltime, na.rm=TRUE), 2), 
                " Mean: ", round(mean(dem$traveltime, na.rm=TRUE), 2), sep=""))
  }
  
  st_write(hf_points, paste("Data/R output/hf_ncentroids_", i, ".shp", sep=""), append=FALSE)
}

#########################################################
##### Analyze the data #####

#As per my usual setup, I took the shp file generated above and
#used the Distance Allocation tool in ArcGIS to calculate the
#travel time to each facility.
#The control in this scenario uses the same set of populated
#points as both demand points and candidate points. 
control  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_control.tif")
cent60  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_60.tif")
cent100  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_100.tif")
cent200  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_200.tif")
cent400  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_400.tif")
cent600  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_600.tif")
cent800  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_800.tif")
cent1000  <- rast("Data/Travel Time Catchments/test - centroids/ttpercatch_ncentroids_1000.tif")

control <- resample(control, temp, method="bilinear")
cent60 <- resample(cent60, temp, method="bilinear")
cent100 <- resample(cent100, temp, method="bilinear")
cent200 <- resample(cent200, temp, method="bilinear")
cent400 <- resample(cent400, temp, method="bilinear")
cent600 <- resample(cent600, temp, method="bilinear")
cent800 <- resample(cent800, temp, method="bilinear")
cent1000 <- resample(cent1000, temp, method="bilinear")

#Make a dataframe to show the travel time to HF given each scenario
allstack <- c(grid3_100m, control, cent60, cent100, cent200, cent400, cent600, cent800, cent1000)
names(allstack) <- c("pop", "control", "60centroids", "100centroids", "200centroids", "400centroids",
                     "600centroids", "800centroids", "1000centroids")
allstack <- as.data.frame(allstack, xy=TRUE, na.rm=TRUE)
#Also make a longer version of the data
allstack_piv <- allstack %>% pivot_longer(cols=4:12, names_to="scenario", values_to="traveltime")
allstack_piv$scenario <- gsub("centroids", "", allstack_piv$scenario)
allstack_piv$scenario <- factor(allstack_piv$scenario, levels=c("control", "60", "100", "200", "400", "600", "800", "1000"))

#Make a violin plot of the data
ggplot() + 
  geom_violin(data=allstack_piv, aes(x=scenario, y=traveltime, weight=pop, fill=scenario)) + 
  coord_flip() + 
  theme(legend.position="none") + 
  labs(y="Travel time (minutes)", x="centroids") + 
  scale_y_continuous(breaks=seq(0, 2500, by=150))

#Calculate the min, max, and mean travel time per scenario
allstack_piv %>% group_by(scenario) %>% 
  summarize(mintt = min(`traveltime`), maxtt = max(`traveltime`), meantt = mean(`traveltime`))

#Calculate several percentiles of travel time per scenario
apply(allstack[4:11], 2, quantile, probs = c(0.05, 0.25, 0.5, 0.75, 0.95), na.rm = TRUE)

#Calculate the total # of populated points w/in 2h of a facility
allstack_piv %>% 
  filter(`traveltime` <= 120) %>% 
  group_by(scenario) %>% 
  summarize(cellstot = n(), cellsprop = (n() / nrow(allstack))*100)

#Calculate the total population w/in 2h of a facility
allstack_piv %>% 
  filter(`traveltime` <= 120) %>% 
  group_by(scenario) %>% 
  summarize(ppltot = sum(pop), proptot = 100*(sum(pop)/sum(allstack$pop)))